=== JairoGC-1812/SEWextraordinaria/xml/rutas.dtd
<?xml version = "1.0" encoding = "utf-8"?>
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (tipos, tiempo,agencia, descripcion, personas-adecuadas, inicio, coordenadas, referencias, recomendacion, hitos, planimetria, altimetria)>

<!ATTLIST ruta nombre CDATA #REQUIRED>
<!ATTLIST ruta dificultad CDATA #REQUIRED>
<!ATTLIST ruta transporte CDATA #REQUIRED>

<!ELEMENT tipos (tipo+)>
<!ELEMENT tipo (#PCDATA)>

<!ELEMENT tiempo EMPTY>
<!ATTLIST tiempo duracion CDATA #REQUIRED>
<!ATTLIST tiempo fecha-inicio CDATA #IMPLIED>
<!ATTLIST tiempo hora-inicio CDATA #IMPLIED>

<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

<!ELEMENT personas-adecuadas (#PCDATA)>

<!ELEMENT inicio EMPTY>
<!ATTLIST inicio lugar CDATA #REQUIRED direccion CDATA #REQUIRED>

<!ELEMENT coordenadas EMPTY>
<!ATTLIST coordenadas longitud CDATA #REQUIRED>
<!ATTLIST coordenadas latitud CDATA #REQUIRED>
<!ATTLIST coordenadas altitud CDATA #REQUIRED>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT recomendacion (#PCDATA)>

<!ELEMENT hitos (hito+)>
<!ELEMENT hito (descripcion, coordenadas, imagenes, videos?)>
<!ATTLIST hito nombre CDATA #REQUIRED>
<!ATTLIST hito distancia-desde-anterior CDATA #IMPLIED>
<!ATTLIST hito unidades-de-distancia CDATA #IMPLIED>

<!ELEMENT imagenes (imagen+)>
<!ELEMENT imagen (#PCDATA)>

<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT planimetria (#PCDATA)>
<!ELEMENT altimetria (#PCDATA)>

=== JairoGC-1812/SEWextraordinaria/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas> -->

<rutas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="rutas.xsd">
  <ruta nombre="Ruta los Molinos del Ríu Profundu" dificultad="Baja" transporte="A pie">
    <tipos>
      <tipo> Etnografía </tipo>
      <tipo> Paisajes </tipo>
      <tipo> Naturaleza </tipo>
    </tipos>
    <tiempo duracion="5 horas" fecha-inicio="2023-06-10" hora-inicio="09:00:00" />

    <agencia> Sin agencia</agencia>

    <descripcion>Una de las rutas más atractivas de Villaviciosa. Tramo de 7km con ruinas de antiguos molinos de agua rodeados de bosque de ribera</descripcion>

    <personas-adecuadas>Adecuado para niños </personas-adecuadas>

    <inicio lugar="Valbúcar" direccion="AS-255, 9, Villaviciosa, Asturias" />
    <coordenadas latitud="43.461328" longitud="-5.438658" altitud="34" />

    <referencias>
      <referencia> https://www.turismovillaviciosa.es/ruta-de-los-molinos-del-rio-profundu/villaviciosa </referencia>
      <referencia> https://www.cotoyapindia.com/2019/06/ruta-de-los-molinos-pr-ast-137.html </referencia>
      <referencia> https://es.wikiloc.com/rutas-senderismo/la-ruta-de-los-molinos-del-rio-profundo-villaviciosa-25280188</referencia>
    </referencias>

    <recomendacion> 8 </recomendacion>

    <hitos>
      <hito nombre="Molín de Griselda" distancia-desde-anterior="0.5" unidades-de-distancia="km">
        <descripcion> Ruinas del Molín de Griselda, directamente visible desde el camino de la ruta</descripcion>
        <coordenadas latitud="43.460210" longitud="-5.434374" altitud="31" />
        <imagenes>
          <imagen> ./multimedia/molin_griselda.jpg </imagen>
        </imagenes>
      </hito>

      <hito nombre="Molín de Villaverde" distancia-desde-anterior="1.2" unidades-de-distancia="km">
        <descripcion> Ruinas del Molín de Villaverde, un poco más alejado del camino de la ruta pero rodeado de precioso bosque autóctono</descripcion>
        <coordenadas latitud="43.456533" longitud="-5.424323" altitud="54" />
        <imagenes>
          <imagen> ./multimedia/molin_villaverde.jpg </imagen>
        </imagenes>
      </hito>

      <hito nombre="Molín el Pitu" distancia-desde-anterior="0.5" unidades-de-distancia="km">
        <descripcion> Ruinas del Molín El Pitu. Casi totalmente rodeadas de vegetación pero con un encanto especial. En su interior se puede observar la rueda original</descripcion>
        <coordenadas latitud="43.452277" longitud="-5.421454" altitud="63" />
        <imagenes>
          <imagen> ./multimedia/molin_pitu1.jpg </imagen>
          <imagen> ./multimedia/molin_pitu2.jpg </imagen>
        </imagenes>
      </hito>

      <hito nombre="Molín de Perniles" distancia-desde-anterior="1.4" unidades-de-distancia="km">
        <descripcion> En O Pedrouzo los peregrinos hacen su última parada antes de la llegada a Santiago de Compostela. Se trata de un pequeño núcleo urbano perteneciente a la parroquia de Arca, que a su vez forma parte del municipio de O Pino. </descripcion>
        <coordenadas latitud="43.450349" longitud="-5.408034" altitud="102" />
        <imagenes>
          <imagen> ./multimedia/molin_perniles1.jpg </imagen>
          <imagen> ./multimedia/molin_perniles2.jpg </imagen>
        </imagenes>
      </hito>

      <hito nombre="Molín la Peña" distancia-desde-anterior="1.8" unidades-de-distancia="km">
        <descripcion> El molín La Peña es el mejor conservado y más conocido de la ruta, con la cascada junto a la que se encuentra </descripcion>
        <coordenadas latitud="43.439629" longitud="-5.397353" altitud="145" />
        <imagenes>
          <imagen> ./multimedia/molin_peña.jpg </imagen>
        </imagenes>
        <videos>
          <video> ./multimedia/molin_peña.mp4</video>
        </videos>
      </hito>
            <hito nombre="Molín d'Arriba" distancia-desde-anterior="1.0" unidades-de-distancia="km">
        <descripcion> El molín d'Arriba es el último de esta ruta y otro de los que mejor se conserva. Se encuentra cerca de la aldea de Busllaz. </descripcion>
        <coordenadas latitud="43.433653" longitud="-5.391802" altitud="180" />
        <imagenes>
          <imagen> ./multimedia/darriba.jpg </imagen>
        </imagenes>
      </hito>
    </hitos>
    <planimetria></planimetria>
    <altimetria></altimetria>
  </ruta>
</rutas>
